### ISSUE TITLE
How to use with authorizer

### ISSUE THREAD

**Issue by brandonhilkert** [jamesdixon/ember-cli-simple-auth-firebase#3]
Seems like the other `ember-simple-auth` libs have an authorizer too. I'd like to protect some routes from the user's data. I feel like I'm missing something about this part...

**Comment by jamesdixon** [comment]
@brandonhilkert if you just want to prevent users from accessing areas of your application if they aren't authenticated, you can just use the `AuthenticatedRouteMixin` [provided by Ember Simple Auth](http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-AuthenticatedRouteMixin). The reason I didn't build a custom Authorizer is because the Firebase library creates its own token in localstorage once authenticated, which is used by the library to authenticate each of its calls. If you're looking for more fine-grained control, you'll have to dig into the Firebase security rules. Hope this helps. If I'm missing something here, lemme know.

James

**Comment by brandonhilkert** [comment]
Nah, you're right. Silly question. I realized it probably as you were typing this. If you don't mind, the part that I'm stuck on now is creating records in context of the user for multi-tenancy. I realize that's not part of this project, but would really value any feedback you have.

**Comment by jamesdixon** [comment]
Can you be a bit more specific?

**Comment by brandonhilkert** [comment]
I'm attempting to use the authorization: https://www.firebase.com/docs/web/guide/understanding-security.html#section-authorization

And it seems like in order to create records underneath an `$user_id`, you'd have to use an authorize to pass the `auth` in when creating?

I'm grasping on to just about anything at this point b/c the data mode feels so foreign to me coming from a more traditional API background.

**Comment by jamesdixon** [comment]
Yeah, the Firebase rules are a bit confusing at first and require your data to be structured in a way that allows their rules to work. When you've authenticated, you'll see a token in local storage that contains the auth id. That auth id can be referenced in your security rules via the `auth` variable. That is automatically passed into calls. If you did nothing else in your security rules but check for `auth !== null` then technically anyone who has been authenticated could access any of your data. To secure it for specific users, you'll have to use something like `$user_id === auth.id` where `$`user_id` is just passed in as part of the path. This security guide might be a bit more in depth and give you what you're looking for: https://www.firebase.com/docs/security/guide/user-security.html

**Comment by brandonhilkert** [comment]
I have something like that now:

```
    "clients": {
      "$user_id": {
        ".read": "(auth != null) && ($user_id === auth.uid)",
        ".write": "(auth != null) && ($user_id === auth.uid)"
      }
    }
```

And for some reason, it doesn't seem to be getting the auth info: http://cl.ly/image/032f2Y0B2F0l

That's why I thought you had to do something additional to get it to pass the auth info to firebase on each request. Maybe I'm doing something else wrong though.

**Comment by jamesdixon** [comment]
I believe i know what the issue is.

When you use Firebase's built-in authentication, it stores that auth data in a hidden node. The user id's are in the form of `[provider]:[id]`, so `[provider]` would be 'simpleauth' for their email/password authentication. That said, if you want to create a "clients" area, you'd have to create the user via their authentication, grab the id (ex: `simpleauth:82`) and then create a node under your "clients" area where the key is the id you just grabbed, so the path would end up being `/clients/simpleauth:82`. With your current ruleset, `simpleauth:82` would end up being `$user_id` and would be equal to `auth.id`. Currently, it looks like you're creating the clients node with `push()`, which ends up creating a unique id, but it's not the actual user id.
